### ISSUE TITLE
Skill Final Level does not display update

### ISSUE THREAD

**Issue by slumberer** [harliq/Weenie-Fab#24]
The Skill Final Level text box on the Attribs/Skills pane only ever displays the last data input into it. I assume this is supposed to update based on the row selected and show you the Skill Final Level for that row, which it does not. I can't seem to find that value anywhere without doing the math myself to derive it.
![y1yS3MKb2U](https://user-images.githubusercontent.com/28830094/89833553-1bc6d380-db16-11ea-89b5-9cdecfdb2d7d.gif)
Hopefully that gif shows you what I mean.

**Comment by harliq** [comment]
Fixed in Version 0.9.8.8
