### ISSUE TITLE
Issue with emotes 

### ISSUE THREAD

**Issue by LawrencePW** [harliq/Weenie-Fab#38]
Hi,
first of all ... thank you for that great tool. I like it.

I try to work with emotes and want to use your tool but I found some strange thing. I am using the version 0.9.9.6.
The problem is: I create a weenie with some emotes and work on it, save it. Everything looks fine. Reloading it then some emote commands are gone. 
Even if I load a weenie, save it as a copy and reload it with Weenie-Fab some emotes are gone.

Original Weenie:
https://drive.google.com/file/d/1VeUBLRdaX406VJj5Zt24Enpob78qfrtm/view?usp=sharing

Weenie saved and reloaded:
https://drive.google.com/file/d/1tSxYjs7Nl4WA2_Wq4ybWlecNH-Ex_F5v/view?usp=sharing

**Comment by harliq** [comment]
This is due to an issue with ES, I am just sending the sql emotes to ES for it to be converted.  Same with converting the ES to sql emotes.

**Comment by PsyberTrigger** [comment]
WeenieFab.v0.9.9.9
Issue short description: 
    After INSERT INTO `weenie_properties_attribute_2nd` the emote script doesn't terminate the sql line with a semi-colon (;) and results in an error upon trying to execute it with the following INSERT INTO  `weenie_properties_emote`... see picture of where I found the missing ; 
![Untitled](https://user-images.githubusercontent.com/49579586/155645208-97eaae3f-2727-44b0-8ed9-7c9dae26e574.png)

**Comment by PsyberTrigger** [comment]
About the above, I realized 9.9.909 is current, tried it, reproduced the same issue successfully.
