### ISSUE TITLE
Releases won't run on Windows 10 64-bit version 1909

### ISSUE THREAD

**Issue by rushcodes** [harliq/Weenie-Fab#44]
When I try to launch the .exe of several different versions, including the latest from the release page - I get the following error:

---------------------------
WeenieFab.exe
---------------------------
To run this application, you must install .NET Core.

The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found.

Would you like to download it now?
---------------------------
Yes   No   
---------------------------

I've downloaded 3.1.20 x86 and x64 and I still get the error. So I then downloaded 3.1.0 x86 and x64 - and I still get the same error.

**Comment by ghostchillidog** [comment]
I've just had a similar issue. I went to the .NET Core page and there's a link for a .NET *Desktop* Runtime. Downloaded this (x64) and installed, Weenie Factory starts now.

Link to MS download page:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.26-windows-x64-installer
